# This is the default format.
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:title

markdown: kramdown
kramdown:
  toc_levels: 1..3
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
highlighter: rouge

# Content enhancement features
reading_time: true
words_per_minute: 200
related_posts: true
related_posts_max: 5

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : Ideia.me
tagline: Tags
author :
  name : Jônatas Davi Paganini
  email : jonatasdp@gmail.com
  github : jonatas
  twitter : jonatasdp
  linkedin: jonatasdp
  instagram: jonatasdp
  feedburner : ideiame
  avatar: "/images/jonatas-davi-paganini-profile-2025.png"
  bio: "Senior developer and technical consultant with 20+ years of experience specializing in PostgreSQL, TimescaleDB, and distributed systems. Expert in database optimization, microservices architecture, and team enablement. Passionate about sharing knowledge through writing, speaking, and mentoring."

# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : https://ideia.me

